name: Update Portfolio

on:
  schedule:
    - cron: "0,30 6-13 * * 1-5"
    - cron: "0 0-5,14-23 * * 1-5"
    - cron: "0 0,2,4,6,8,10,12,14,16,18,20,22 * * 6,0"
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-portfolio:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run Portfolio Update
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: python backend/run_update.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "rudrap31"
          git config --global user.email "3rudrap1@gmail.com"
          git add portfolio.json
          git commit -m "Update portfolio.json"
          git push
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
